# Generated by Django 6.0.7 on 2026-07-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phonenumber_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
