# Generated by Django 6.0.7 on 2026-07-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='added_ad',
            new_name='added_at',
        ),
    ]
